# This file was generated by GoReleaser. DO NOT EDIT.
cask "clank" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "1b10264dff5bba34c342a582eaf47b02bbe344c58aa5195b7074e56c4699aee7"
      url "https://github.com/supaclank/clank/releases/download/v#{version}/clank_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "36f7a4eda8919a24c5fbabea08d2cbb52d90106639eae3b6f5bde8c37065d19c"
      url "https://github.com/supaclank/clank/releases/download/v#{version}/clank_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "02e59f14b3c0348113bb6cd7321a53998a1124caabb618ee15ce58f531446eb6"
      url "https://github.com/supaclank/clank/releases/download/v#{version}/clank_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4e0d13d71cfefc1376fd5a5770270cfc1912118c2bd3b27031f741ad73a80f1c"
      url "https://github.com/supaclank/clank/releases/download/v#{version}/clank_#{version}_linux_arm64.tar.gz"
    end
  end

  name "clank"
  desc "Visually editable previews for web & mobile, powered by your own coding agents"
  homepage "https://github.com/supaclank/clank"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clank"
  binary "clankd"
  binary "clank-host"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Push-to-talk dictation in `clank preview` needs the optional voice
    engine, built from source on your machine:
      brew install supaclank/tap/clank-voice
  EOS
end
