# This file was generated by GoReleaser. DO NOT EDIT.
cask "clank" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "f4de8ff89d3157ded18b9b8848d19e9ebf5062f4215ff7cebe5f70cf5faca139"
      url "https://github.com/supaclank/clank/releases/download/v#{version}/clank_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4ee9564be89f8c2425f67f914473f4fda9d689479e384a79d2b79977e7747438"
      url "https://github.com/supaclank/clank/releases/download/v#{version}/clank_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5abecac7d2293eb237005651f015a54c50a5174103cb5d2c8770b1495c2b8b27"
      url "https://github.com/supaclank/clank/releases/download/v#{version}/clank_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7de2b8f86fa1e1ac237696030c85e768adae4c3ff77be97785d74d4a63ab33c2"
      url "https://github.com/supaclank/clank/releases/download/v#{version}/clank_#{version}_linux_arm64.tar.gz"
    end
  end

  name "clank"
  desc "Visually editable previews for web & mobile, powered by your own coding agents"
  homepage "https://github.com/supaclank/clank"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clank"
  binary "clankd"
  binary "clank-host"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Push-to-talk dictation in `clank preview` needs the optional voice
    engine, built from source on your machine:
      brew install supaclank/tap/clank-voice
  EOS
end
