# This file was generated by GoReleaser. DO NOT EDIT.
cask "clank" do
  version "0.3.6"

  on_macos do
    on_arm do
      sha256 "43210f12af2a7198a69c74f2595b4c0caaf904c925e07f6ff298557533d8ae4f"
      url "https://github.com/supaclank/clank/releases/download/v#{version}/clank_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "33d0cc71b8c52b453bb7c2801670d4b00662bb83263d09a5c422e7ce8050463d"
      url "https://github.com/supaclank/clank/releases/download/v#{version}/clank_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0ae3ae3f5031cbee139f864da48ed653599c5e6c177a698ba3a47da8527949a4"
      url "https://github.com/supaclank/clank/releases/download/v#{version}/clank_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8ce99393415c5324ad671e3e536840016ff1aa1009bfc502978f226c03587d25"
      url "https://github.com/supaclank/clank/releases/download/v#{version}/clank_#{version}_linux_amd64.tar.gz"
    end
  end

  name "clank"
  desc "Visually editable previews for web & mobile, powered by your own coding agents"
  homepage "https://github.com/supaclank/clank"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clank"
  binary "clankd"
  binary "clank-host"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Push-to-talk dictation in `clank preview` needs the optional voice
    engine, built from source on your machine:
      brew install supaclank/tap/clank-voice
  EOS
end
